# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/Users/kylegolcynski/Documents/GitHub/Project-Creator/MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_DocumentCreationWidget(object):
    def setupUi(self, DocumentCreationWidget):
        DocumentCreationWidget.setObjectName("DocumentCreationWidget")
        DocumentCreationWidget.resize(400, 500)
        self.verticalLayout = QtWidgets.QVBoxLayout(DocumentCreationWidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.templateList = QtWidgets.QListView(DocumentCreationWidget)
        self.templateList.setObjectName("templateList")
        self.verticalLayout.addWidget(self.templateList)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.destinationFolder = QtWidgets.QLineEdit(DocumentCreationWidget)
        self.destinationFolder.setReadOnly(True)
        self.destinationFolder.setObjectName("destinationFolder")
        self.horizontalLayout.addWidget(self.destinationFolder)
        self.browseButton = QtWidgets.QPushButton(DocumentCreationWidget)
        self.browseButton.setObjectName("browseButton")
        self.horizontalLayout.addWidget(self.browseButton)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.nameLineEdit = QtWidgets.QLineEdit(DocumentCreationWidget)
        self.nameLineEdit.setObjectName("nameLineEdit")
        self.verticalLayout.addWidget(self.nameLineEdit)
        self.createButton = QtWidgets.QPushButton(DocumentCreationWidget)
        self.createButton.setObjectName("createButton")
        self.verticalLayout.addWidget(self.createButton)

        self.retranslateUi(DocumentCreationWidget)
        QtCore.QMetaObject.connectSlotsByName(DocumentCreationWidget)

    def retranslateUi(self, DocumentCreationWidget):
        _translate = QtCore.QCoreApplication.translate
        DocumentCreationWidget.setWindowTitle(_translate("DocumentCreationWidget", "Document Creation From Template"))
        self.destinationFolder.setToolTip(_translate("DocumentCreationWidget", "Choose an existing directory to save the new project in.<br />Click <i>Browse</i> if you would like to specify a different location."))
        self.destinationFolder.setPlaceholderText(_translate("DocumentCreationWidget", "Location"))
        self.browseButton.setText(_translate("DocumentCreationWidget", "Browse..."))
        self.nameLineEdit.setToolTip(_translate("DocumentCreationWidget", "Enter the name of your project.<br />A new folder called <i>Name</i> will be created in <i>Location</i> with the following name.<br /><i>Name</i> must be a valid folder name that doesn\'t already exist inside <i>Location</i>."))
        self.nameLineEdit.setPlaceholderText(_translate("DocumentCreationWidget", "Name"))
        self.createButton.setText(_translate("DocumentCreationWidget", "Create Template"))
